### ISSUE TITLE
Params with Accept-Encoding: gzip doesnt decode (deflate?)

### ISSUE THREAD

**Issue by JALIMA** [arquimedescrivelari/foxpages#5]
Hi,
could you pls helps me to know how must decode this Params,  when i debug doesnt decode correctly.

Actually the procedure finds two parameters as well, but when try to decode doesnt decode correclty,  i Wish to know how proceed to decode 

Then... With this 2 parameters i must to return the result from a query,  could you pls tell me if  I must to response after send "200 Ok" code? with another POST?     or in  the same response?

I really apreciate your help.

I receive the following Request

POST /rdc?method=query2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 147
Host: 192.168.43.132:17178
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.12.12

xœaf```dÉù¹¹‰y)ŒÒ@N’I¢^jEbnANª^nbfžJ|JTXðKÌMeä2ŠSsR“KâK‹K‹2ó¹€B‰E@Ù’Ô¢b1&zXph€kP˜g°:—Èõ,öÌË,ÉLÌÉ¬JMagddŠådæf–€ìƒ¸°h\f~HÆ

**Comment by arquimedescrivelari** [comment]
Hi,

I'm coming back from vacation, sorry for the delay.

I don't know how to decode the content of the request because I don't have any information about how it was encoded. We need to use the content-coding or content-encoding http header to send this information.

I cannot find an RFC on data encryption or compression using an x-www-form-urlencoded post. So, in my opinion, this is an invalid request. You said you are trying to return data from a query. In this case, I recommend using a GET with query string. For example:

GET / rdc?method=query2&param1=abcd&param2=1234 HTTP / 1.1
Host: 192.168.43.132:17178
Connection: Keep-Alive
Accept-Encoding: gzip
User agent: okhttp / 3.12.12

Keep in mind that the GET method must be used for queries and the POST method to send data.

Regards,

Arquimedes Crivelari
